name: Check PR
on:
  push:
    branches-ignore:
      - main
      - develop
      - 'release/**'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-job@v1
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v1
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:jest
